#!/bin/bash
# Add JWT configuration to .env file

set -euo pipefail

CERTS_DIR="${CERTS_DIR:-./certs}"

if [ ! -f "$CERTS_DIR/jwt-private-key.pem" ]; then
    echo "❌ JWT keys not found. Run 'task gen-jwt-keys' first"
    exit 1
fi

if [ ! -f .env ]; then
    echo "❌ .env file not found"
    exit 1
fi

echo "⚙️  Configuring JWT in .env..."

# Remove existing JWT config
sed -i.bak '/^JWT_ALGORITHM=/d' .env
sed -i.bak '/^JWT_PRIVATE_KEY_FILE=/d' .env
sed -i.bak '/^JWT_PUBLIC_KEY_FILE=/d' .env

# Add new JWT config
cat >> .env <<EOF

# JWT Configuration (generated by task configure-jwt-env)
JWT_ALGORITHM=RS256
JWT_PRIVATE_KEY_FILE=$CERTS_DIR/jwt-private-key.pem
JWT_PUBLIC_KEY_FILE=$CERTS_DIR/jwt-public-key.pem
EOF

rm -f .env.bak

echo "✅ JWT configuration added to .env"
echo "💡 Server will now use RSA JWT signing"
