#!/bin/bash
# Add TLS configuration to .env file

set -euo pipefail

CERTS_DIR="${CERTS_DIR:-./certs}"

if [ ! -f "$CERTS_DIR/server-cert.pem" ] || [ ! -f "$CERTS_DIR/server-key.pem" ]; then
    echo "❌ TLS certificates not found. Run 'task gen-tls-certs' first"
    exit 1
fi

if [ ! -f .env ]; then
    echo "❌ .env file not found"
    exit 1
fi

echo "⚙️  Configuring TLS in .env..."

# Remove existing TLS config
sed -i.bak '/^TLS_ENABLED=/d' .env
sed -i.bak '/^TLS_CERT_FILE=/d' .env
sed -i.bak '/^TLS_KEY_FILE=/d' .env

# Add new TLS config
cat >> .env <<EOF

# TLS Configuration (generated by task configure-tls-env)
TLS_ENABLED=true
TLS_CERT_FILE=$CERTS_DIR/server-cert.pem
TLS_KEY_FILE=$CERTS_DIR/server-key.pem
EOF

rm -f .env.bak

echo "✅ TLS configuration added to .env"
echo "💡 Server will now use HTTPS on port \${PORT}"
